#Database
spring.datasource.url=jdbc:mysql://localhost:3306/db_book_rental?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username=root
spring.datasource.password=1234567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.sqlScriptEncoding=UTF-8
spring.jpa.properties.hibernate.jdbc.time_zone = UTC
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Config format and timezone UTC for request and response JSON
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=UTC

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
#logging.level.org.springframework=DEBUG

#Server port
server.port=8383

#Config swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.defaultModelsExpandDepth=-1

# Config not null
spring.jackson.default-property-inclusion=non_null

# Jwt secret
jwt.signerKey="GMJABr4EsQc0zeq6l78w/xsngbR9e5MsFQBz8yoHKrc5Q85PUj1xrGA6C6dTVbKv"

# Token expires
jwt.access-token-validity=86400
jwt.refresh-token-validity=604800
